
--MQL
SELECT MEMBER_CODE
    FROM MEMBER
    WHERE ID= 'ID1' AND PASSWORD = 'PWD'
;

DESC MEMBER;

--CODE => TO_CHAR(SYSDATE,'YYMIDDMMSSHH24')로 할 예정 // 년 - 분 - 일 - 월 - 일 - 시간
SELECT TO_CHAR(SYSDATE,'YYMIDDMMSSHH24---')||USER_CODE_SEQUENCE.nextval FROM DUAL; 

INSERT INTO MEMBER VALUES (TO_CHAR(SYSDATE,'YYMIDDMMSSHH24')||USER_CODE_SEQUENCE.nextval,'ID16','PWD',01012345690,'ID16@NAVER.COM');

SELECT * FROM MEMBER;