
--MQL
SELECT MEMBER_CODE
    FROM MEMBER
    WHERE ID= 'ID1' AND PASSWORD = 'PWD'
;

DESC MEMBER;

--CODE => TO_CHAR(SYSDATE,'YYMIDDMMSSHH24')로 할 예정 // 년 - 분 - 일 - 월 - 초 - 시간 --- 시퀸스
SELECT TO_CHAR(SYSDATE,'YYMIDDMMSSHH24---')||USER_CODE_SEQUENCE.nextval FROM DUAL; 

INSERT INTO MEMBER VALUES (TO_CHAR(SYSDATE,'YYMIDDMMSSHH24')||USER_CODE_SEQUENCE.nextval,'ID16','PWD',01012345690,'ID16@NAVER.COM');


SELECT * FROM MEMBER;

SELECT COUNT(*) FROM MEMBER WHERE ID='687';

commit;

SELECT 'ASDF@naver,com'||'' FROM DUAL;

DESC MEMBER;


SELECT ID , PASSWORD, PHONE , EMAIL FROM MEMBER WHERE MEMBER_CODE=20240412;

UPDATE MEMBER SET PASSWORD = 'PWD2' , PHONE = '01001010101' , EMAIL = '변경@성공'  WHERE member_code = '20240414';

SELECT MEMBER_CODE FROM MEMBER WHERE ID='ID1' AND PASSWORD='PWD';

SELECT * FROM MEMBER;

UPDATE MEMBER SET PHONE='123456789012345' WHERE MEMBER_CODE =24051904261514;

DESC RESTORANT_OWNER;
SELECT * FROM RESTORANT_OWNER;
INSERT INTO RESTORANT_OWNER VALUES (TO_CHAR(SYSDATE,'YYMIDDMMSSHH24')||USER_CODE_SEQUENCE.nextval , 20240412); 