
---DROP SEQUENCE
DROP SEQUENCE USER_CODE_SEQUENCE;


-------DROP TABLE
DROP TABLE "RESTORANT_INFO";
DROP TABLE "MEMBER_DELIVER_INFO";
DROP TABLE "MENU";
DROP TABLE "RESTORANT_REVIEW";
DROP TABLE "RESTORANT";
DROP TABLE "RESTORANT_OWNER";
DROP TABLE "MEMBER";


--------CREATE TABLE
CREATE TABLE "MEMBER" (
	"MEMBER_CODE"	VARCHAR2(20)		NOT NULL,
	"ID"	        VARCHAR2(30)		NOT NULL    UNIQUE,
	"PASSWORD"	    VARCHAR2(30)		NOT NULL,
	"PHONE"	        NUMBER		        NULL        UNIQUE,
	"EMAIL"	        VARCHAR2(30)		NULL        UNIQUE
);

COMMENT ON COLUMN "MEMBER"."MEMBER_CODE" IS '회원 고유 코드 PRIMARY KEY';

COMMENT ON COLUMN "MEMBER"."ID" IS '아이디 UNIQUE';

COMMENT ON COLUMN "MEMBER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '휴대폰 번호 UNIQUE';

COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일 UNIQUE @없으면 오류';





CREATE TABLE "RESTORANT_OWNER" (
	"OWNER_CODE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_CODE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "RESTORANT_OWNER"."OWNER_CODE" IS '가게 사장 고유 코드';

COMMENT ON COLUMN "RESTORANT_OWNER"."MEMBER_CODE" IS '회원 고유 코드 PRIMARY KEY';





CREATE TABLE "RESTORANT" (
	"RESTORANT_CODE"	    VARCHAR2(20)		NOT NULL,
	"OWNER_CODE"	        VARCHAR2(20)		NOT NULL,
	"RESTORANT_NAME"	    NVARCHAR2(20)		NOT NULL,
	"RESTORANT_PHONE"	    NUMBER		        NOT NULL    UNIQUE,
	"RESTORANT_SUB_PHONE"	NUMBER		        NULL        UNIQUE,
	"RESTORANT_EMAIL"	    VARCHAR2(30)		NOT NULL    UNIQUE,
	"RESTORANT_LOCAL"	    NVARCHAR2(50)		NOT NULL,
	"RESTORANT_MESSAGE"	    NVARCHAR2(300)		NULL,
	"RESTORANT_KIND"	    VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "RESTORANT"."RESTORANT_CODE" IS '레스토랑 고유 번호 PRIMARY KEY';

COMMENT ON COLUMN "RESTORANT"."OWNER_CODE" IS '가게 사장 고유 코드';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_NAME" IS '레스토랑 이름';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_PHONE" IS '레스토랑 번호UNIQUE';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_SUB_PHONE" IS '레스토랑 보조 번호, NULL 가능 UNIQUE';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_EMAIL" IS '레스토랑 이메일 UNIQUE';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_LOCAL" IS '레스토랑 지역 -API로 위치 뜨게';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_MESSAGE" IS '등록된 가게 설명';

COMMENT ON COLUMN "RESTORANT"."RESTORANT_KIND" IS '레스토랑 음식 분야';




CREATE TABLE "MENU" (
	"MENU_NUM"	        NUMBER		        NOT NULL,
	"RESTORANT_CODE"	VARCHAR2(20)		NOT NULL,
	"MENU_NAME"     	VARCHAR2(10)		NOT NULL,
	"MENU_IMAGE"	    VARCHAR2(10)		NULL,
	"MENU_COMMENT"	    VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "MENU"."MENU_NUM" IS '메뉴 번호';

COMMENT ON COLUMN "MENU"."RESTORANT_CODE" IS '레스토랑 고유 번호 PRIMARY KEY';

COMMENT ON COLUMN "MENU"."MENU_NAME" IS '메뉴 이름';

COMMENT ON COLUMN "MENU"."MENU_IMAGE" IS '메뉴 사진';

COMMENT ON COLUMN "MENU"."MENU_COMMENT" IS '메뉴 상세 설명';


CREATE TABLE "MEMBER_DELIVER_INFO" (
	"DELIVER_NUMBER"	NUMBER		                NOT NULL,
	"RESTORANT_CODE"	VARCHAR2(20)		        NOT NULL,
	"MENU_NUM"	        NUMBER		                NOT NULL,
    "MENU_MOUNT"        NUMBER                      NOT NULL,
	"DISPOSABLE"	    CHAR(1)	        DEFAULT 'N'	NOT NULL,
	"TO_DLIVER"	        NVARCHAR2(25)		        NULL,
	"TO_RESTORANT"	    NVARCHAR2(50)		        NULL,
	"MEMBER_ADRESS"	    NVARCHAR2(50)		        NOT NULL
);

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."DELIVER_NUMBER" IS '주문번호';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."RESTORANT_CODE" IS '레스토랑 고유 번호 PRIMARY KEY';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."MENU_NUM" IS '메뉴 번호';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."DISPOSABLE" IS '일회용품 필요 유무 Y또는 N';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."TO_DLIVER" IS '기사님께 드릴 말씀';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."TO_RESTORANT" IS '가게에 드릴 말씀';

COMMENT ON COLUMN "MEMBER_DELIVER_INFO"."MEMBER_ADRESS" IS '회원 거주지';




CREATE TABLE "RESTORANT_INFO" (
	"RESTORANT_CODE"	VARCHAR2(20)		        NOT NULL,
	"PLACE_ALONE"	    CHAR(1)	        DEFAULT 'N'	NULL,
	"PLACE_GROUP"	    CHAR(1)	        DEFAULT 'N'	NULL,
	"SIT_FLOOR"	        CHAR(1)	        DEFAULT 'N'	NULL,
	"SIT_CHAIR"	        CHAR(1)	        DEFAULT 'N'	NULL,
	"STANDING"	        CHAR(1)	        DEFAULT 'N'	NULL
);

COMMENT ON COLUMN "RESTORANT_INFO"."RESTORANT_CODE" IS '레스토랑 고유 번호 PRIMARY KEY';

COMMENT ON COLUMN "RESTORANT_INFO"."PLACE_ALONE" IS '혼밥석 유무';

COMMENT ON COLUMN "RESTORANT_INFO"."PLACE_GROUP" IS '그룹석 유무';

COMMENT ON COLUMN "RESTORANT_INFO"."SIT_FLOOR" IS '좌식';

COMMENT ON COLUMN "RESTORANT_INFO"."SIT_CHAIR" IS '의자';

COMMENT ON COLUMN "RESTORANT_INFO"."STANDING" IS '서서 식사';




CREATE TABLE "RESTORANT_REVIEW" (
	"REVIEW_CODE"	    VARCHAR2(20)		                    NOT NULL,
	"MEMBER_CODE"	    VARCHAR2(20)		                    NOT NULL,
	"RESTORANT_CODE"	VARCHAR2(20)		                    NOT NULL,
	"REVIEW_NUMBER" 	NUMBER		                            NOT NULL,
	"REVIEW_COMMENT"	NVARCHAR2(300)		                    NOT NULL,
	"REVIEW_DATE"	    TIMESTAMP	                        	NOT NULL,
	"REVIEW_SCORE"	    NUMBER		                            NOT NULL
);

COMMENT ON COLUMN "RESTORANT_REVIEW"."REVIEW_CODE" IS '리뷰 고유 번호 PRIMARYKEY';

COMMENT ON COLUMN "RESTORANT_REVIEW"."MEMBER_CODE" IS '회원 고유 코드 PRIMARY KEY';

COMMENT ON COLUMN "RESTORANT_REVIEW"."RESTORANT_CODE" IS '레스토랑 고유 번호 PRIMARY KEY';

COMMENT ON COLUMN "RESTORANT_REVIEW"."REVIEW_NUMBER" IS '리뷰번호';

COMMENT ON COLUMN "RESTORANT_REVIEW"."REVIEW_COMMENT" IS '리뷰 내용';

COMMENT ON COLUMN "RESTORANT_REVIEW"."REVIEW_DATE" IS '이뷰일';

COMMENT ON COLUMN "RESTORANT_REVIEW"."REVIEW_SCORE" IS '리뷰 점수';





------------PRIMARY KEY
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_CODE"
);

ALTER TABLE "RESTORANT" ADD CONSTRAINT "PK_RESTORANT" PRIMARY KEY (
	"RESTORANT_CODE"
);

ALTER TABLE "RESTORANT_REVIEW" ADD CONSTRAINT "PK_RESTORANT_REVIEW" PRIMARY KEY (
	"REVIEW_CODE"
);

ALTER TABLE "MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY (
	"MENU_NUM"
);

ALTER TABLE "MEMBER_DELIVER_INFO" ADD CONSTRAINT "PK_MEMBER_DELIVER_INFO" PRIMARY KEY (
	"DELIVER_NUMBER"
);

ALTER TABLE "RESTORANT_OWNER" ADD CONSTRAINT "PK_RESTORANT_OWNER" PRIMARY KEY (
	"OWNER_CODE"
);

ALTER TABLE "RESTORANT_INFO" ADD CONSTRAINT "PK_RESTORANT_INFO" PRIMARY KEY (
	"RESTORANT_CODE"
);



----------------FOREGIN KEY
ALTER TABLE "RESTORANT" ADD CONSTRAINT "FK_RESTORANT_OWNER_TO_RESTORANT_1" FOREIGN KEY (
	"OWNER_CODE"
)
REFERENCES "RESTORANT_OWNER" (
	"OWNER_CODE"
);


ALTER TABLE "RESTORANT_REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_RESTORANT_REVIEW_1" FOREIGN KEY (
	"MEMBER_CODE"
)
REFERENCES "MEMBER" (
	"MEMBER_CODE"
);

ALTER TABLE "RESTORANT_REVIEW" ADD CONSTRAINT "FK_RESTORANT_TO_RESTORANT_REVIEW_1" FOREIGN KEY (
	"RESTORANT_CODE"
)
REFERENCES "RESTORANT" (
	"RESTORANT_CODE"
);



ALTER TABLE "MENU" ADD CONSTRAINT "FK_RESTORANT_TO_MENU_1" FOREIGN KEY (
	"RESTORANT_CODE"
)
REFERENCES "RESTORANT" (
	"RESTORANT_CODE"
);

ALTER TABLE "MEMBER_DELIVER_INFO" ADD CONSTRAINT "FK_RESTORANT_TO_MEMBER_DELIVER_INFO_1" FOREIGN KEY (
	"RESTORANT_CODE"
)
REFERENCES "RESTORANT" (
	"RESTORANT_CODE"
);

ALTER TABLE "MEMBER_DELIVER_INFO" ADD CONSTRAINT "FK_MENU_TO_MEMBER_DELIVER_INFO_1" FOREIGN KEY (
	"MENU_NUM"
)
REFERENCES "MENU" (
	"MENU_NUM"
);


ALTER TABLE "RESTORANT_OWNER" ADD CONSTRAINT "FK_MEMBER_TO_RESTORANT_OWNER_1" FOREIGN KEY (
	"MEMBER_CODE"
)
REFERENCES "MEMBER" (
	"MEMBER_CODE"
);

ALTER TABLE "RESTORANT_INFO" ADD CONSTRAINT "FK_RESTORANT_TO_RESTORANT_INFO_1" FOREIGN KEY (
	"RESTORANT_CODE"
)
REFERENCES "RESTORANT" (
	"RESTORANT_CODE"
);

---CREATE SEQUENCE

CREATE SEQUENCE USER_CODE_SEQUENCE
    START WITH 10
    INCREMENT BY 1
    MAXVALUE 99
    MINVALUE 10
    CYCLE
    CACHE 5
    ;


